apiVersion: v1
kind: Service
metadata:
  name: tf-python
spec:
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 8080
          protocol: TCP
    selector:
        app: tf-python